name: Test
on: [push, pull_request]
# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ["1.20"]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: go mod download && go test -race -covermode atomic -coverprofile=./coverage.out.tmp -coverpkg=./... ./...
      - name: Install coveralls
        run: curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz
      - name: Report coverage
        run: ./coveralls --file ./coverage.out.tmp
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
